//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.20 at 09:43:44 AM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wstutorial.com/ws/TutorialService")
package com.wstutorial.ws.tutorialservice;
